version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: mushroom-postgis-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mushroomdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: